spring.application.name=perizinan-ocr-tool

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:mysql://localhost:3306/perizinan_ocr_tool

# spring.jpa.hibernate.ddl-auto=create

perizinan-dpmptsp.api.base-url=http://sistem-informasi-dinas-pmptsp.me/api